apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skeleton-ingress
  namespace: skeleton
  annotations:
    cert-manager.io/cluster-issuer: skeleton-ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - skeleton.local
      secretName: skeleton-tls-secret
  rules:
    - host: skeleton.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skeleton-app-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: skeleton-app-backend
                port:
                  number: 8000
          - path: /health
            pathType: Exact
            backend:
              service:
                name: skeleton-app-backend
                port:
                  number: 8000