grafana:
  nodeSelector:
    role: monitoring
  adminPassword: admin123
  plugins: []
  grafana.ini:
    plugins:
      allow_loading_unsigned_plugins: ""
  # Data sources kao kod
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
      isDefault: false
  livenessProbe:
    initialDelaySeconds: 300
    timeoutSeconds: 30
    failureThreshold: 10
  readinessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 30
    failureThreshold: 10
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 200m

prometheusOperator:
  nodeSelector:
    role: monitoring

prometheus:
  prometheusSpec:
    nodeSelector:
      role: monitoring
    retention: 24h
    additionalScrapeConfigs:
      - job_name: "backend-direct"
        static_configs:
          - targets: ["skeleton-app-backend.skeleton.svc.cluster.local:8000"]
        metrics_path: /metrics
        scrape_interval: 15s
alertmanager:
  enabled: false

kube-state-metrics:
  nodeSelector:
    role: monitoring

prometheus-node-exporter:
  nodeSelector:
    role: monitoring