apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: skeleton
spec:
  # ClusterIP = dostupan samo unutar klastera (sto i zelimo za DB)
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
