apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "skeleton-app.fullname" . }}
  labels:
    app: {{ include "skeleton-app.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: skeleton-tls-secret
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "skeleton-app.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "skeleton-app.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.port }}